export const plans = [
	{
		title: "Launch",
		icon: "material-symbols:rocket-launch-outline",
		byline: "Kickstart your idea and launch fast!",
		currency: "USD",
		symbol: "$",
		amount: "600",
		discount: "450",
		features: [
			"One-time payment",
			"Standard website - up to 7 pages",
			"90+ PageSpeed score",
			"100% Image Optimization and Full CDN caching via Cloudflare Enterprise",
			"100% Google, SEO, and mobile-friendly",
			"Google Analytics",
			"Secured Forms",
		],
		button: "Launch now",
	},
	{
		title: "Growth",
		icon: "material-symbols:monitoring",
		byline: "Grow and expand your horizon!",
		currency: "USD",
		symbol: "$",
		amount: "1200",
		discount: "750",
		features: [
			"All Launch Plan features",
			"Premium website development - up to 15 pages",
			"95+ PageSpeed score",
			"Custom Dashboard and CMS",
			"Integration with your desired CRM",
			"Detailed Reports and Analytics",
			"3 months free maintenance",
		],
		button: "Grow now",
	},
	{
		title: "Domination",
		icon: "material-symbols:social-leaderboard-outline",
		byline: "Dominate your market!",
		currency: "USD",
		symbol: "$",
		amount: "1800",
		discount: "1200",
		features: [
			"All Growth Plan features",
			"Custom web development - unlimited pages",
			"99+ PageSpeed score",
			"Personalized Digital Experience",
			"Ecommerce store and Secured Checkout",
			"Advanced Sales Reports",
			"6 months free maintenance",
		],
		button: "Dominate now",
	},
];
